#!/bin/bash

# 脚本名称：generate_antlr.sh
# 用途：生成 Antlr C++ 代码并清理目录结构

# 设置变量
ANTLR_JAR="thirdparty/antlr4/antlr-4.12.0-complete.jar"
GRAMMAR_FILE="frontend/antlr4/MiniC.g4"
OUTPUT_DIR="frontend/antlr4/autogenerated"

# 确保脚本在项目根目录下运行
cd "$(dirname "$0")"

# 生成 Antlr C++ 代码
echo "生成 Antlr C++ 代码..."
java -jar $ANTLR_JAR -Dlanguage=Cpp -no-listener -visitor -o $OUTPUT_DIR $GRAMMAR_FILE

# 进入 autogenerated 目录
echo "进入 autogenerated 目录..."
cd $OUTPUT_DIR

# 将 frontend/antlr4/ 下的所有文件移动到当前目录
echo "移动生成的文件到当前目录..."
mv frontend/antlr4/* .

# 删除 frontend/antlr4 文件夹
echo "删除 frontend/antlr4 文件夹..."
rm -rf frontend/antlr4

# 删除 frontend 文件夹
echo "删除 frontend 文件夹..."
rm -rf frontend

# 返回项目根目录
echo "返回项目根目录..."
cd ../../..

echo "Antlr 代码生成和目录清理完成！"